config/routes.rb
Rails.application.routes.draw do
  resources :apologies
  resources :incidents
  devise_for :users, skip: [:sessions] , controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  as :user do
    get '/signup', to: 'devise/registrations#new', as: :new_user
    get 'signin', to: 'devise/sessions#new', as: :new_user_session
    post 'signin', to: 'devise/sessions#create', as: :user_session
    get 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  resources :users, only: [:show]

  root to: "home#index"

  #here we're sending a put request with the id of the apology we want to forgive and we are calling our forgive method in our controller
  put '/apology/:id/forgiveness', to: 'apologies#forgive', as: 'forgiveness'
  delete '/apology/:id/forgiveness', to: 'apologies#unforgive'

  get '/newest_apologies', to: 'apologies#newest_apologies'

  get '/users/:id/forgivenesses', to: 'apologies#forgivenapologies'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
      @apologies = Apology.newest_apologies
      @longest_apologies = Apology.long_apology
      @users = User.all
      @incidents = Incident.all
  end

  def newest_apologies
    @apologies = Apology.newest_apologies
  end

end

app/helpers/home_helper.rb
module HomeHelper

    def all_users
        @users.each do |user|
            "#{link_to user.name, user} "
        end
    end

    def all_incidents
        "all incidents"
    end

    def longest_apologies
        "longest apologies"
    end

    def newest_apologies
        "newest apologies"
    end

end

app/views/home/_home.html.erb
<h3><a href='/newest_apologies'>Newest Apologies</a></h3>

<h3>Longest Apologies</h3>
<%= render 'longest_apologies' %>
<h3>All Users</h3>
<%= render 'users'%>
</ul>
<h3>All Incidents</h3>
<%= render 'incidents' %>

app/views/home/_incidents.html.erb
<ul>
 <% @incidents.each do |incident| %>
 <li> <%=link_to incident.name, incident_path(incident) %>, (<%=incident.apologies_count%>)</li>
 <%end%>
</ul>

app/views/home/_longest_apologies.html.erb
<ul>
<% Apology.long_apology.each do |apology|%>
<li><%= apology.user.name%> apologizes for <%= link_to apology.incident.name, apology_path(apology)%> (<%= apology.body.split.size%> words)
<%end%>
</ul>

app/views/home/_users.html.erb
<ul>
 <% @users.each do |user| %>
 <li> <%=link_to user.name, user_path(user) %> </li>
 <%end%>
</ul>

app/views/home/index.html.erb
<% if user_signed_in? %>
<%= render 'home'%>
<% end %>